### PR TITLE
fix(data-explorer): remove tabs bug

### PR DESCRIPTION
**Pull request by alili**

### CODE REVIEW

**Comment by sunng87** [comment]
The result data in table is incorrect when any tab closed. Steps to reproduce:

- Run three different queries to get three different result tabs
- close one of them 
- check remaining tabs

**Comment by sunng87** [comment]
I confirm the issue has been fixed. Please rebase to resolve conflict.

**Review by ZonaHex — APPROVED** [review]
LGTM

**Review by alili — COMMENTED** [review]
fix chart drawing with watch

**Pull request merged**
