### PR TITLE
feat: support promQL

### PR DESCRIPTION
**Pull request by ZonaHex**
Check out the new PR: #187 

PromQL edit and execute #103
- [x] Add PromQL CodeMirror editor. Toggle to change editor type.
- [x] Add absolute/relative time range select.
- [ ] Test API.
- [ ] Change UI and update with current main code.
- [ ] Logs support promQL

### CODE REVIEW

**Comment by ZonaHex** [comment]
start/end/step params are not working (server side) right now.

**Comment by ZonaHex** [comment]
Might need to add new info in Logs

**Comment by waynexia** [comment]
> start/end/step params are not working (server side) right now.

It's supported in https://github.com/GreptimeTeam/greptimedb/pull/985

**Comment by ZonaHex** [comment]
Check out the new PR: https://github.com/GreptimeTeam/dashboard/pull/187

**Pull request closed without merging**
